name: flutter_uploader
description: A plugin for creating and managing upload tasks with optional background exection support.
version: 3.0.0-beta.4
homepage: https://github.com/fluttercommunity/flutter_uploader
maintainer: Sebastian Roth (@ened)

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.bluechilli.flutteruploader
        pluginClass: FlutterUploaderPlugin
      ios:
        pluginClass: FlutterUploaderPlugin
